TIME_CONSTANT = 5                                       # Number of time steps that make on day

N_INDIVIDUALS_DEFAULT = 250                             # Chosen
LATTICE_SIZE_DEFAULT = 50                               # Chosen
INITIAL_INFECTION_RATE_DEFAULT = 0.01                   # Chosen

MOVING_RATE_RANGE_DEFAULT = [0.6, 0.8]                  # Chosen
PRESYMPTOMATIC_STAGE_MOVEMENT_FREEDOM = 1.              # Chosen
DETECTED_STAGE_MOVEMENT_FREEDOM = 1.                    # Chosen

INFECTION_PROBABILITY_DEFAULT = 0.5                     # Chosen
SYMPTOMATIC_INFECTION_PROBABILITY_DEFAULT = 0.85        # From the paper

AVERAGE_DAYS_OF_IMMUNITY = 75.                          # Coording to CDC, after recovery, each individual has at leaset 2-3 months of immunity
AVERAGE_DAYS_UNTIL_DITECTING_SYMPTOMATIC_INDIVIDUAL = 3.# Chosen
AVERAGE_DAYS_UNTIL_BECOMING_PRESYMPATIC = 4.            # From the paper
AVERAGE_DAYS_UNTIL_BECOMING_CONTAGIOUS = 4.             # From the paper
AVERAGE_DAYS_UNTIL_RECOVERY_AFTER_DETECTION = 4.        # Chosen
AVERAGE_DAYS_UNTIL_RECOVERY_WITHOUT_DETECTION = 15.     # From the paper

IMMUNITY_PROBABILITY = 1#-1./(AVERAGE_DAYS_OF_IMMUNITY*TIME_CONSTANT)                         
SYMPTOMATIC_DETECTION_PROBABILITY_DEFAULT = 1./(AVERAGE_DAYS_UNTIL_DITECTING_SYMPTOMATIC_INDIVIDUAL*TIME_CONSTANT)
BECOMING_PRESYMPATIC_ROBABILITY_DEFAULT = 1./(AVERAGE_DAYS_UNTIL_BECOMING_PRESYMPATIC*TIME_CONSTANT)
BECOMING_CONTAGIOUS_PROBABILITY_DEFAULT = 1./(AVERAGE_DAYS_UNTIL_BECOMING_CONTAGIOUS*TIME_CONSTANT)
RECOVERY_AFTER_DETECTION_PROBABILITY_DEFAULT = 1./(AVERAGE_DAYS_UNTIL_RECOVERY_AFTER_DETECTION*TIME_CONSTANT)
RECOVERY_WITHOUT_DETECTION_PROBABILITY_DEFAULT = 1./(AVERAGE_DAYS_UNTIL_RECOVERY_WITHOUT_DETECTION*TIME_CONSTANT)

average_recovery_steps_in_symptomatic_infection = (SYMPTOMATIC_DETECTION_PROBABILITY_DEFAULT/RECOVERY_AFTER_DETECTION_PROBABILITY_DEFAULT+RECOVERY_WITHOUT_DETECTION_PROBABILITY_DEFAULT)/(SYMPTOMATIC_DETECTION_PROBABILITY_DEFAULT+RECOVERY_AFTER_DETECTION_PROBABILITY_DEFAULT)

AVERAGE_INFECTION_DAYS = (1/BECOMING_PRESYMPATIC_ROBABILITY_DEFAULT +\
                          1/BECOMING_CONTAGIOUS_PROBABILITY_DEFAULT +\
                         (1-SYMPTOMATIC_INFECTION_PROBABILITY_DEFAULT)*(1/RECOVERY_WITHOUT_DETECTION_PROBABILITY_DEFAULT) +\
                         SYMPTOMATIC_INFECTION_PROBABILITY_DEFAULT * average_recovery_steps_in_symptomatic_infection)/TIME_CONSTANT


TRACED_INDIVIDUALS_FRACTION_DEFAULT = 0.4               # Chosen
DAYS_TO_TRAC_INDIVIDUALS = AVERAGE_INFECTION_DAYS

TEST_ACCURACY = 0.95                                    # According to the information on available test for covid

N_TIME_STEPS_TO_TRACE_DEFAULT = int(DAYS_TO_TRAC_INDIVIDUALS*TIME_CONSTANT)


# Total covid cases and death (Dec 2nd)
# Cases: 264M             Deaths: 5,22M
# Assume: Getting detected can increase the chance of survival by a factor of three
FATALITY_AFTER_DETECTION_PROBABILITY_DEFAULT = 0       # 5.22/264.*(0.5)/TIME_CONSTANT
FATALITY_BEFORE_DETECTION_PROBABILITY_DEFAULT = 0      # 5.22/264.*(1.5)/TIME_CONSTANT

INITIALLY_TESTED_POPULATION_FRACTION = 0.00